Draft: Use API V2 for get classes
Criador-Horarios/Criador-Horarios pull request #82
Opened 2023-09-09 20:05 UTC by masterzeus05

2023-09-09 22:43 UTC, diogotcorreia commented
Shifts don't appear to be showing :thinking: 

![image](https://github.com/Criador-Horarios/Criador-Horarios/assets/7467891/2742a231-0132-4c13-bd9f-af53575043db)

I'm using the deploy preview link above.

As a side note: the API v2 now allows cross-origin requests on public endpoints, we don't need to proxy the requests anymore (might improve performance).

2023-09-10 15:08 UTC, diogotcorreia requested changes

2023-09-10 15:08 UTC, diogotcorreia commented on src/domain/Degree.ts
>  }
No newline :(

2023-09-10 15:08 UTC, diogotcorreia commented on src/domain/Shift.ts
> +			const endTime = new Date(l.end).toLocaleTimeString()
To allow for users in other timezones, perhaps we should convert the date to a local date on `Europe/Lisbon`?

2023-09-10 16:28 UTC, diogotcorreia approved these changes

2023-09-10 16:40 UTC, joaocmd approved these changes

2023-09-10 17:00 UTC, merged